import { useQuery } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Award, BadgeCheck, Flame, ShieldCheck, Sparkles, Trophy } from 'lucide-react';
import { useAuth } from '../auth/AuthContext';
import type { CSSProperties } from 'react';
import { PageMotion } from '../../shared/PageMotion';
import { getProfile } from './dashboardApi';
import './journey-rewards.css';

const number = new Intl.NumberFormat('en-IN');
const statLabels = [['total_awards', 'Verified actions'], ['leaderboard_xp', 'Competitive XP'], ['deliveries', 'Deliveries'], ['clean_bookings', 'Clean bookings'], ['fast_deliveries', 'Fast deliveries'], ['escalations_resolved', 'Escalations resolved'], ['cancellation_saves', 'Cancellation saves'], ['cross_dept_assists', 'Cross-department assists']] as const;

export function JourneyPage() {
  const token = useAuth().session!.accessToken; const { data: user } = useQuery({ queryKey: ['profile'], queryFn: () => getProfile(token) });
  const xp = user ? Math.min(100, user.current_level_xp / Math.max(user.next_level_xp, 1) * 100) : 0;
  return <PageMotion><section className="journey-header"><div><p className="eyebrow">MY JOURNEY / VERIFIED PROGRESSION</p><h1>{user?.name ?? 'Your'} <em>drive.</em></h1><p>{user?.designation ?? 'Team member'} · {user?.department ?? 'Department loading'} · {user?.location_code ?? 'Location loading'}</p></div><div className="rank-stack"><span><Trophy size={15} /> All-time rank</span><strong>#{user?.all_time_rank ?? '—'}</strong></div></section><section className="journey-grid"><article className="dash-card level-card"><span className="level-number">{user?.level ?? '—'}</span><div><p className="eyebrow">CURRENT TITLE</p><h2>{user?.title ?? 'Loading title'}</h2><div className="progress-track"><motion.span animate={{ width: `${xp}%` }} /></div><p>{number.format(user?.current_level_xp ?? 0)} of {number.format(user?.next_level_xp ?? 0)} XP in this level</p></div></article><article className="dash-card reputation-card"><div className="reputation-ring" style={{ '--reputation': `${user?.reputation ?? 0}%` } as CSSProperties}><span>{user?.reputation ?? '—'}<small>/100</small></span></div><div><p className="eyebrow">REPUTATION</p><h2>Play clean.</h2><p>A backend-calculated measure of quality, collaboration, and resilient work—not a second XP meter.</p></div></article><article className="dash-card streak-card"><Flame /><p className="eyebrow">MILESTONE STREAK</p><strong>{user?.current_streak ?? '—'} <small>days</small></strong><span>Longest verified streak: {user?.longest_streak ?? '—'} days</span></article></section><section className="journey-content"><article className="dash-card"><div className="card-heading"><span><Award size={17} /> PERFORMANCE RECORD</span><span>{number.format(user?.total_awards ?? 0)} awards</span></div><div className="performance-list">{statLabels.map(([key, label]) => <div key={key}><span>{label}</span><strong>{number.format(user?.[key] ?? 0)}</strong></div>)}</div><p className="rework-note"><ShieldCheck size={14} /> {user?.rework_discounted_awards ?? 0} awards include a rework discount, preserving fair recognition.</p></article><article className="dash-card badge-card trophy-garage"><div className="card-heading"><span><BadgeCheck size={17} /> TROPHY GARAGE</span><span>{user?.badges.length ?? 0} unlocked</span></div><div className="badges">{user?.badges.length ? user.badges.map((badge, index) => <motion.div className="badge" key={badge.code} initial={{ opacity: 0, scale: .85 }} animate={{ opacity: 1, scale: 1 }} transition={{ delay: index * .06 }} title={badge.description}><Sparkles size={18} /><strong>{badge.name}</strong><span>{badge.description}</span></motion.div>) : <p>No badges have been awarded yet. Verified milestones unlock them here.</p>}</div></article></section></PageMotion>;
}
