import { AnimatePresence, motion } from 'framer-motion';
import { CarFront, Check, Copy, Gauge, Medal, Settings2, Share2, Trophy, Volume2, VolumeX, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Profile, QuestBoard } from '../../types/api';
import { DriverGarage } from './GarageExperience';
import { awardNextGarageItem } from './garageCatalog';
import './enhancements.css';
import './player-card.css';
import './player-avatar.css';

export { DriverGarage };
export const awardNextCosmetic = awardNextGarageItem;
let celebrationAudio: AudioContext | null = null;
export const playRewardSound = async () => { if (localStorage.getItem('carverse.sound') !== 'on' || !window.AudioContext) return; celebrationAudio ??= new window.AudioContext(); const context = celebrationAudio; if (context.state === 'suspended') await context.resume(); const start = context.currentTime + .02; [0, .1, .2, .34, .48].forEach((delay, index) => { const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = index === 4 ? 'triangle' : 'sine'; oscillator.frequency.setValueAtTime([523, 659, 784, 1047, 1319][index], start + delay); gain.gain.setValueAtTime(.0001, start + delay); gain.gain.exponentialRampToValueAtTime(index === 4 ? .18 : .11, start + delay + .015); gain.gain.exponentialRampToValueAtTime(.0001, start + delay + .3); oscillator.connect(gain).connect(context.destination); oscillator.start(start + delay); oscillator.stop(start + delay + .32); }); };
export function PitWall({ profile, quests }: { profile?: Profile; quests?: QuestBoard }) { const next = quests?.quests.find(quest => !quest.claimed); return <aside className="pit-wall"><span><Gauge size={14}/> PIT WALL</span><strong>Level {profile?.level ?? '-'} · {profile?.current_streak ?? 0}d streak</strong><p>{next ? `${next.progress}/${next.target_count} · ${next.title}` : 'All current missions complete'}</p></aside>; }
export function PlayerCard({ profile, quests }: { profile?: Profile; quests?: QuestBoard }) { const next = quests?.quests.find(quest => !quest.claimed); const name = profile?.name ?? 'Loading driver'; return <article className="player-card"><div className="player-card__glow"/><div className="player-card__top"><span><Trophy size={15}/> PLAYER PROFILE CARD</span><b>LVL {profile?.level ?? '-'}</b></div><div className="player-card__identity"><div className="player-card__avatar" aria-label="Racing driver avatar"><i className="player-card__helmet"/><i className="player-card__visor"/><i className="player-card__suit"/></div><div><h3>{name}</h3><p>{profile?.designation ?? profile?.department ?? 'Dealership competitor'}</p><small>{profile?.department ?? 'DEALERSHIP'} · {profile?.location_code ?? 'MULTI-BRANCH'}</small></div></div><div className="player-card__stats"><span><b>{profile?.total_xp ?? 0}</b> LIFETIME XP</span><span><b>{profile?.total_awards ?? 0}</b> REWARDS</span><span><b>{profile?.badges.length ?? 0}</b> TROPHIES</span></div><div className="player-card__achievements"><p>ACHIEVEMENT CABINET</p>{profile?.badges.slice(0, 3).map(badge => <span key={badge.code}><Medal size={14}/>{badge.name}</span>) ?? null}{!profile?.badges.length && <span><Medal size={14}/> First verified milestone unlocks your first trophy</span>}</div><footer><span>UP NEXT: <b>{next?.title ?? 'All missions cleared'}</b></span><strong>#{profile?.all_time_rank ?? '—'} ALL-TIME</strong></footer></article>; }
export function SoundControl() { const [on, setOn] = useState(() => localStorage.getItem('carverse.sound') === 'on'); const change = () => { const next = !on; setOn(next); localStorage.setItem('carverse.sound', next ? 'on' : 'off'); if (next) void playRewardSound(); }; return <button className="icon-button" onClick={change} aria-label={on ? 'Disable achievement sounds' : 'Enable achievement sounds'}>{on ? <Volume2 size={16}/> : <VolumeX size={16}/>}</button>; }
export function AchievementCinematic({ title, open, onClose, artifact }: { title: string; open: boolean; onClose: () => void; artifact?: string | null }) { useEffect(() => { if (open && title) void playRewardSound(); }, [open, title]); return <AnimatePresence>{open && <motion.div className="achievement-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} role="dialog" aria-modal="true">{[...Array(18)].map((_, index) => <motion.i key={index} style={{ position: 'fixed', left: '50%', top: '45%', width: 8, height: 8, background: index % 2 ? '#e9fb6b' : '#ff5e56', borderRadius: '50%' }} initial={{ opacity: 1, scale: 0 }} animate={{ opacity: [1, 1, 0], x: Math.cos(index) * ((index % 6) + 4) * 42, y: Math.sin(index) * ((index % 6) + 4) * 42, rotate: index * 45, scale: 1 }} transition={{ duration: 1.4, delay: .08 }}/>) }<motion.div initial={{ scale: .7, y: 30, rotateX: -18 }} animate={{ scale: 1, y: 0, rotateX: 0 }} exit={{ scale: .8 }} className="achievement-card"><button onClick={onClose} aria-label="Close achievement"><X/></button><motion.div style={{ display: 'grid', placeItems: 'center', width: 112, height: 112, margin: '0 auto 1rem', border: '1px solid #e9fb6b', borderRadius: '50%', background: '#23301c', color: '#e9fb6b', boxShadow: '0 0 40px #e9fb6b55' }} animate={{ rotateY: [0, 360] }} transition={{ duration: 2.2 }}>{artifact?.includes('trophy') ? <Trophy size={74}/> : artifact ? <CarFront size={76}/> : <Medal size={58}/>}</motion.div><p className="eyebrow">HURRAY · VERIFIED REWARD</p><h2>{title}</h2><p>{artifact ? `New cosmetic unlocked: ${artifact}. Visit Driver Garage to equip it.` : 'The pit crew has recorded your latest milestone.'}</p><Check size={22}/></motion.div></motion.div>}</AnimatePresence>; }
export function ShareRecap({ text, title }: { text?: string; title: string }) { const [done, setDone] = useState(false); const canShare = 'share' in navigator; const share = async () => { const content = `${title}\n${text ?? 'CarVerse verified performance recap.'}`; try { if (canShare) await navigator.share({ title, text: content }); else { await navigator.clipboard.writeText(content); setDone(true); } } catch { /* User dismissed the native share sheet. */ } }; return <button className="button button--ghost" onClick={() => void share}>{done ? <><Check size={14}/> Copied</> : canShare ? <><Share2 size={14}/> Share</> : <><Copy size={14}/> Copy recap</>}</button>; }
export function ReplayButton({ onReplay }: { onReplay: () => void }) { return <button className="button button--ghost" onClick={onReplay}><Settings2 size={14}/> Replay verified journey</button>; }
