import { motion, AnimatePresence } from 'framer-motion';
import { CarFront, Check, Copy, Gauge, Medal, Settings2, Share2, Trophy, Volume2, VolumeX, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import type { Profile, QuestBoard } from '../../types/api';
import './enhancements.css';
import { ThreeGarage } from './ThreeGarage';

const liveries = ['Volt Lime', 'Signal Red', 'Cobalt Blue', 'Stealth Silver'];
const playRewardSound = () => { if (localStorage.getItem('carverse.sound') !== 'on') return; const AudioCtx = window.AudioContext; if (!AudioCtx) return; const ctx=new AudioCtx(); [0,.09,.18,.3].forEach((delay,index)=>{const oscillator=ctx.createOscillator();const gain=ctx.createGain();oscillator.type=index===3?'triangle':'sine';oscillator.frequency.setValueAtTime(520+index*180,ctx.currentTime+delay);gain.gain.setValueAtTime(.0001,ctx.currentTime+delay);gain.gain.exponentialRampToValueAtTime(.14,ctx.currentTime+delay+.01);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+delay+.22);oscillator.connect(gain).connect(ctx.destination);oscillator.start(ctx.currentTime+delay);oscillator.stop(ctx.currentTime+delay+.24)});setTimeout(()=>void ctx.close(),800) };
const rewards = ['Signal Red livery', 'Cobalt Blue race trail', 'Stealth Silver wheel set', 'Neon underglow kit', 'Carbon spoiler', 'Champion trophy', 'Gold pit-crew helmet', 'Victory tyre set'];
const inventoryKey = (employeeId: string) => `carverse.cosmetics.v2.${employeeId}`;
const loadInventory = (employeeId: string) => JSON.parse(localStorage.getItem(inventoryKey(employeeId)) ?? '[]') as string[];
export function awardNextCosmetic(employeeId: string) { const key = inventoryKey(employeeId); const unlocked = loadInventory(employeeId); const next = rewards.find(item => !unlocked.includes(item)); if (!next) return null; localStorage.setItem(key, JSON.stringify([...unlocked, next])); window.dispatchEvent(new Event('carverse-cosmetic-unlocked')); return next; }
export function DriverGarage({ employeeId = 'local' }: { employeeId?: string }) { const [livery, setLivery] = useState(() => localStorage.getItem(`carverse.livery.${employeeId}`) ?? liveries[0]); const [inventory, setInventory] = useState<string[]>(() => loadInventory(employeeId)); useEffect(()=>{const refresh=()=>setInventory(loadInventory(employeeId));window.addEventListener('carverse-cosmetic-unlocked',refresh);return()=>window.removeEventListener('carverse-cosmetic-unlocked',refresh)},[employeeId]); useEffect(()=>localStorage.setItem(`carverse.livery.${employeeId}`,livery),[employeeId,livery]); const allowed=(item:string)=>item==='Volt Lime'||inventory.some(reward=>reward.startsWith(item)); const colors:Record<string,string>={'Volt Lime':'#e9fb6b','Signal Red':'#ff5e56','Cobalt Blue':'#58a6ff','Stealth Silver':'#d7dde8'}; const accessories=inventory.filter(item=>!['Signal Red livery','Cobalt Blue race trail','Stealth Silver wheel set'].includes(item)); return <article className="dash-card garage-card"><div className="card-heading"><span><CarFront size={17}/> DRIVER GARAGE / 3D</span><span>{inventory.length}/{rewards.length} UNLOCKED</span></div><ThreeGarage colour={colors[livery]} accessories={accessories}/><p>Rotate view automatically; earned accessories appear on the 3D car.</p><div className="livery-options">{liveries.map(item=><button key={item} disabled={!allowed(item)} onClick={()=>setLivery(item)} className={item===livery?'selected':''}>{allowed(item)?item:`🔒 ${item}`}</button>)}</div>{accessories.length>0&&<div className="livery-options" style={{marginTop:'.7rem'}}>{accessories.map(item=><span key={item} style={{border:'1px solid #e9fb6b',padding:'.35rem',color:'#e9fb6b',fontSize:'.7rem'}}>✓ {item}</span>)}</div>}</article> }
export function PitWall({ profile, quests }: { profile?: Profile; quests?: QuestBoard }) { const next=quests?.quests.find(q=>!q.claimed); return <aside className="pit-wall"><span><Gauge size={14}/> PIT WALL</span><strong>Level {profile?.level ?? '—'} · {profile?.current_streak ?? 0}d streak</strong><p>{next ? `${next.progress}/${next.target_count} · ${next.title}` : 'All current missions complete'}</p></aside> }
export function SoundControl() { const [on,setOn]=useState(()=>localStorage.getItem('carverse.sound')==='on'); const change=()=>{const next=!on;setOn(next);localStorage.setItem('carverse.sound',next?'on':'off');if(next)playRewardSound()}; return <button className="icon-button" onClick={change} aria-label={on?'Disable achievement sounds':'Enable achievement sounds'}>{on?<Volume2 size={16}/>:<VolumeX size={16}/>}</button> }
export function AchievementCinematic({ title, open, onClose, artifact }: { title: string; open: boolean; onClose: () => void; artifact?: string | null }) { return <AnimatePresence>{open&&<motion.div className="achievement-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true">{[...Array(18)].map((_,i)=><motion.i key={i} style={{position:'fixed',left:'50%',top:'45%',width:8,height:8,background:i%2?'#e9fb6b':'#ff5e56',borderRadius:'50%'}} initial={{opacity:1,scale:0}} animate={{opacity:[1,1,0],x:Math.cos(i)*((i%6)+4)*42,y:Math.sin(i)*((i%6)+4)*42,rotate:i*45,scale:1}} transition={{duration:1.4,delay:.08}}/>)}<motion.div initial={{scale:.7,y:30,rotateX:-18}} animate={{scale:1,y:0,rotateX:0}} exit={{scale:.8}} className="achievement-card"><button onClick={onClose} aria-label="Close achievement"><X/></button><motion.div style={{display:'grid',placeItems:'center',width:112,height:112,margin:'0 auto 1rem',border:'1px solid #e9fb6b',borderRadius:'50%',background:'#23301c',color:'#e9fb6b',boxShadow:'0 0 40px #e9fb6b55'}} animate={{rotateY:[0,360]}} transition={{duration:2.2}}>{artifact?.includes('trophy')?<Trophy size={74}/>:artifact?<CarFront size={76}/>:<Medal size={58}/>}</motion.div><p className="eyebrow">HURRAY · VERIFIED REWARD</p><h2>{title}</h2><p>{artifact ? `New cosmetic unlocked: ${artifact}. Visit Driver Garage to equip it.` : 'The pit crew has recorded your latest milestone.'}</p><Check size={22}/></motion.div></motion.div>}</AnimatePresence> }
export function ShareRecap({ text, title }: { text?: string; title: string }) { const [done,setDone]=useState(false); const canShare='share' in navigator; const share=async()=>{const content=`${title}\n${text??'CarVerse verified performance recap.'}`;try{if(canShare)await navigator.share({title, text:content});else{await navigator.clipboard.writeText(content);setDone(true)}}catch{/* User dismissed share sheet. */}}; return <button className="button button--ghost" onClick={()=>void share()}>{done?<><Check size={14}/> Copied</>:canShare?<><Share2 size={14}/> Share</>:<><Copy size={14}/> Copy recap</>}</button> }
export function ReplayButton({ onReplay }: { onReplay: () => void }) { return <button className="button button--ghost" onClick={onReplay}><Settings2 size={14}/> Replay verified journey</button> }
