import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { useEffect, useRef } from 'react';

export function ThreeGarage({colour,accessories}:{colour:string;accessories:string[]}){
  const host=useRef<HTMLDivElement>(null);
  useEffect(()=>{const node=host.current;if(!node)return;const scene=new THREE.Scene();scene.add(new THREE.GridHelper(18,36,0x52637d,0x263244));const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(5,2.8,6);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.style.cssText='display:block;width:100%;height:100%;touch-action:none';node.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.7,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=4;controls.maxDistance=10;controls.minPolarAngle=.55;controls.maxPolarAngle=1.45;scene.add(new THREE.HemisphereLight(0xffffff,0x10192b,3));const lamp=new THREE.DirectionalLight(0xffffff,3);lamp.position.set(4,6,5);scene.add(lamp);const glow=new THREE.PointLight(colour,35,14);glow.position.set(-2,1,3);scene.add(glow);
    const car=new THREE.Group(),paint=new THREE.MeshPhysicalMaterial({color:colour,metalness:.9,roughness:.16,clearcoat:1,clearcoatRoughness:.12}),glass=new THREE.MeshPhysicalMaterial({color:0x0b1728,metalness:.4,roughness:.08,transparent:true,opacity:.72}),rubber=new THREE.MeshStandardMaterial({color:0x080a0f,roughness:.62,metalness:.25}),chrome=new THREE.MeshStandardMaterial({color:0xaeb9c9,metalness:1,roughness:.18});
    const body=new THREE.Mesh(new THREE.SphereGeometry(1,40,20),paint);body.scale.set(2.05,.52,.9);body.position.y=.7;car.add(body);const hood=new THREE.Mesh(new THREE.SphereGeometry(1,32,18),paint);hood.scale.set(1.22,.18,.76);hood.position.set(-1.2,1.0,0);car.add(hood);const roof=new THREE.Mesh(new THREE.SphereGeometry(1,32,18),glass);roof.scale.set(.93,.43,.7);roof.position.set(.12,1.2,0);car.add(roof);const bumper=new THREE.Mesh(new THREE.SphereGeometry(1,28,14),paint);bumper.scale.set(.23,.26,.75);bumper.position.set(-1.96,.58,0);car.add(bumper);for(const z of[-.88,.88]){const light=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.42),new THREE.MeshStandardMaterial({color:0xe9fb6b,emissive:0xe9fb6b,emissiveIntensity:2}));light.position.set(-2.06,.75,z);car.add(light)}for(const x of[-1.25,1.25])for(const z of[-.86,.86]){const wheel=new THREE.Group();const tyre=new THREE.Mesh(new THREE.CylinderGeometry(.39,.39,.25,32),rubber);tyre.rotation.x=Math.PI/2;wheel.add(tyre);const rim=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.27,18),chrome);rim.rotation.x=Math.PI/2;wheel.add(rim);wheel.position.set(x,.42,z);car.add(wheel)}if(accessories.some(x=>x.includes('spoiler'))){const spoiler=new THREE.Mesh(new THREE.BoxGeometry(.9,.12,1.45),paint);spoiler.position.set(1.65,1.22,0);car.add(spoiler)}if(accessories.some(x=>x.includes('underglow')||x.includes('trail'))){const under=new THREE.PointLight(colour,16,6);under.position.set(0,.22,0);car.add(under)}scene.add(car);
    let frame=0;const draw=()=>{frame=requestAnimationFrame(draw);const w=Math.max(node.clientWidth,1),h=Math.max(node.clientHeight,1);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();controls.update();renderer.render(scene,camera)};draw();return()=>{cancelAnimationFrame(frame);controls.dispose();renderer.dispose();node.replaceChildren()}},[colour,accessories]);
  return <div ref={host} style={{position:'relative',height:300,width:'100%',maxWidth:'100%',overflow:'hidden',border:'1px solid #344056',background:'radial-gradient(circle,#263653,#101622)',cursor:'grab'}}><span style={{position:'absolute',left:12,top:10,color:'#e9fb6b',fontSize:12,pointerEvents:'none'}}>CARVERSE / MATERIALS SHOWROOM</span><span style={{position:'absolute',left:12,bottom:8,color:'#e9fb6b',fontSize:12,pointerEvents:'none'}}>DRAG TO ROTATE · SCROLL TO ZOOM</span></div>
}
