import { useQuery } from '@tanstack/react-query';
import { AnimatePresence, motion } from 'framer-motion';
import { Crown, MonitorPlay, Radio, Trophy, Zap } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useAuth } from '../auth/AuthContext';
import { getBoard, getBosses } from '../dashboard/dashboardApi';
import './tv.css';
import './tv-fix.css';

const number=new Intl.NumberFormat('en-IN');
export function TvPage(){const token=useAuth().session!.accessToken;const [slide,setSlide]=useState(0);const branches=useQuery({queryKey:['tv','branches'],queryFn:()=>getBoard(token,'branch','all'),refetchInterval:20_000});const bosses=useQuery({queryKey:['tv','bosses'],queryFn:()=>getBosses(token),refetchInterval:20_000});useEffect(()=>{const id=window.setInterval(()=>setSlide(s=>(s+1)%3),9000);return()=>window.clearInterval(id)},[]);const top=branches.data?.entries.slice(0,3)??[];return <main className="tv-page"><div className="tv-grid"/><header><div className="brand"><span className="brand-mark">CV</span><span>CARVERSE<span className="brand-dot">.</span></span></div><span className="tv-live"><Radio size={17}/> LOBBY MODE · LIVE GRID</span></header><section className="tv-scoreboard"><span><Zap/> VERIFIED PERFORMANCE ONLY</span><b>TURNING EVERY DEALERSHIP INTO A LEADERBOARD</b><span>SEASON 01 · INDIA</span></section><AnimatePresence mode="wait">{slide===0?<motion.section key="podium" className="tv-slide tv-podium" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:1.04}}><p className="eyebrow">BRANCH CHAMPIONSHIP</p><h1>Who owns<br/>the <em>road?</em></h1><div className="podium">{top.map((entry,index)=><article key={String(entry.location_code)} className={`podium-place place-${index+1}`}><Crown/><strong>#{index+1}</strong><h2>{String(entry.location_name??entry.location_code)}</h2><p>{String(entry.outlet_type??'Dealership branch')}</p><b>{number.format(Number(entry.normalized_score??0))}</b></article>)}</div></motion.section>:slide===1?<motion.section key="boss" className="tv-slide" initial={{opacity:0,x:60}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-60}}><p className="eyebrow">DEPARTMENT RAID / LIVE</p><h1>One grid.<br/><em>Full throttle.</em></h1><div className="tv-bosses">{bosses.data?.battles.slice(0,6).map(b=><article key={b.id}><Trophy/><h2>{b.title}</h2><p>{b.department}</p><div className="boss-bar"><span style={{width:`${Math.min(100,b.progress/Math.max(1,b.target_count)*100)}%`}}/></div><b>{b.progress}/{b.target_count} verified moves</b></article>)}</div></motion.section>:<motion.section key="race" className="tv-slide tv-race" initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-40}}><p className="eyebrow">CARVERSE RACE CONTROL</p><h1>Every handoff<br/>creates <em>momentum.</em></h1><div className="tv-track"><motion.div animate={{left:['2%','92%']}} transition={{duration:5,repeat:Infinity,repeatType:'reverse',ease:'easeInOut'}}>🏎️</motion.div><span>SALES</span><span>FINANCE</span><span>ACCOUNTS</span><span>CARE</span><span>DELIVERY</span></div><p className="tv-callout"><MonitorPlay/> Live dealership actions become XP, missions, trophies, and team progress.</p></motion.section>}</AnimatePresence><footer><span>● VERIFIED DATA</span><i/> <span>CARVERSE DRIVE / LOBBY DISPLAY</span></footer></main>}
