import { useQuery } from '@tanstack/react-query';
import { AnimatePresence, motion } from 'framer-motion';
import { CarFront, Flag, Gauge, Map, Play, RotateCcw, Target, Timer, Users, X, Zap } from 'lucide-react';
import * as React from 'react';
import { useMemo, useState } from 'react';
import { Navigate } from 'react-router-dom';
import { PageMotion } from '../../shared/PageMotion';
import { useAuth } from '../auth/AuthContext';
import { getActiveBookings, getBosses, getProfile, getQuests } from '../dashboard/dashboardApi';
import { usePresentationLeaderboard } from '../gameplay/usePresentationLeaderboard';
import './race-control.css';
import './race-control-grand.css';
import './race-control-explain.css';

const format = new Intl.NumberFormat('en-IN');
const fallbackBranches = [{ name: 'Bengaluru Central', score: 94, code: 'BLR' }, { name: 'Mumbai Performance', score: 81, code: 'BOM' }, { name: 'Delhi North', score: 72, code: 'DEL' }, { name: 'Pune Velocity', score: 63, code: 'PUN' }];
const colours = ['#e9fb6b', '#38d6ff', '#ff6159', '#af82ff', '#ffb74f', '#4ee2ad', '#f26bc7', '#d8e1ee'];
const branchTasks = ['completed clean Finance approvals', 'cleared invoice handoffs without rework', 'recovered a delayed PDI inspection', 'lost time to pending documents', 'waited on a cross-department handoff', 'completed insurance and registration checks'];
const boardName = (entry: Record<string, unknown>) => String(entry.location_name ?? entry.location_code ?? 'Verified branch');
const boardScore = (entry: Record<string, unknown>) => Number(entry.normalized_score ?? entry.leaderboard_xp ?? 0);
type Branch = { name: string; score: number; code: string; colour: string };

function Briefing({ open, close, rank, next, mission, boss, department }: { open: boolean; close: () => void; rank?: number | null; next: string; mission: string; boss: string; department: string }) { return <AnimatePresence>{open && <motion.div className="briefing-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.section className="briefing-card" initial={{ y: 30, scale: .96 }} animate={{ y: 0, scale: 1 }} exit={{ y: 20, opacity: 0 }}><button onClick={close} aria-label="Close briefing"><X size={18}/></button><p className="eyebrow">RACE ENGINEER / 15-SECOND BRIEFING</p><h2>Your grid is <em>set.</em></h2><p className="briefing-lead">A clear starting line for your {department || 'dealership'} shift. Only verified work changes your real score.</p><div className="briefing-grid"><article><Flag/><span>CURRENT RANK</span><strong>{rank ? `#${rank}` : 'Unranked'}</strong></article><article><Timer/><span>NEXT PRIORITY</span><strong>{next}</strong></article><article><Target/><span>FOCUS MISSION</span><strong>{mission}</strong></article><article><Users/><span>TEAM TARGET</span><strong>{boss}</strong></article></div><button className="button button--primary" onClick={close}><Play size={15}/> Start my shift</button></motion.section></motion.div>}</AnimatePresence>; }

function RaceExplanation({ branches, mode }: { branches: Branch[]; mode: 'season' | 'rivalry' }) {
  const leader = branches[0]; const challenger = branches[1]; const trailing = branches[branches.length - 1];
  return <section className="race-explanation"><div><p className="eyebrow">WHY DID THE GRID MOVE?</p><h3>{mode === 'season' ? 'Simulation race narrative' : 'Momentum swing narrative'}</h3></div><div className="race-explanation__cards"><article><b style={{ color: leader?.colour }}>{leader?.code ?? 'P1'}</b><strong>{leader?.name}</strong><p>{mode === 'season' ? `Takes the lead after ${branchTasks[0]}; clean, verified handoffs create the strongest pace.` : `Protects position with ${branchTasks[1]}, but must sustain this pace to stay ahead.`}</p></article><article><b style={{ color: challenger?.colour }}>{challenger?.code ?? 'P2'}</b><strong>{challenger?.name}</strong><p>{mode === 'season' ? `Closes the gap after ${branchTasks[1]}, but starts behind because its verified pace is lower.` : `Surges after ${branchTasks[2]}. The simulation shows this branch overtaking when the extra verified work arrives.`}</p></article><article><b style={{ color: trailing?.colour }}>{trailing?.code ?? 'P4'}</b><strong>{trailing?.name}</strong><p>Falls back in the demo because it {branchTasks[3]}. The lesson: stalled handoffs cost momentum until the next valid team action.</p></article></div><small>SIMULATION EXPLANATION ONLY - REAL RANKS STILL COME EXCLUSIVELY FROM VERIFIED BACKEND EVENTS.</small></section>;
}

function SeasonCircuit({ branches }: { branches: Branch[] }) {
  const [run, setRun] = useState(0); const [running, setRunning] = useState(false); const ordered = useMemo(() => [...branches].sort((a, b) => b.score - a.score), [branches]);
  const race = () => { setRunning(true); setRun(value => value + 1); window.setTimeout(() => setRunning(false), 3600); };
  return <section className="race-module season-module season-module--grand"><div className="module-heading"><span><Flag size={16}/> DEALERSHIP GRAND PRIX / SEASON 01</span><small>7-DAY SPRINT · LIVE PACE + DEMO RACE</small></div><div className="grand-intro"><div><h2>The whole dealership<br/>races for the <em>flag.</em></h2><p>Each colour is a branch. Their starting positions reflect live normalized branch pace. Simulate a verified-action race to show every branch moving, overtaking, and finishing.</p><div className="season-actions"><button className="button button--primary" onClick={race} disabled={running}><Play size={15}/>{running ? 'Race in progress...' : 'Simulate verified branch race'}</button><button className="button button--ghost" onClick={() => { setRun(0); setRunning(false); }}><RotateCcw size={15}/> Reset race</button></div><small className="simulation-note">DEMO MODE · SIMULATED MOTION NEVER WRITES XP OR CHANGES THE LIVE LEAGUE</small></div><div className="grand-legend">{ordered.map((branch, index) => <span key={branch.code}><i style={{ background: branch.colour }}/><b>#{index + 1}</b> {branch.name}<small>{format.format(branch.score)} pace</small></span>)}</div></div><div className="grand-scroll"><div className="grand-track">{['START GRID', 'SECTOR 1', 'PIT WINDOW', 'SECTOR 2', 'FINAL LAP', 'CHEQUERED FLAG'].map((label, index) => <div className="grand-marker" key={label} style={{ left: `${index * 19.5 + 3}%` }}><span>{label}</span></div>)}{ordered.map((branch, index) => { const base = 7 + Math.min(18, branch.score / Math.max(1, ordered[0].score) * 16); const target = Math.min(93, base + (run ? 37 + (ordered.length - index) * 3 + (run % 2 && index === 1 ? 7 : 0) : 0)); return <motion.div className="grand-car" key={branch.code} animate={{ left: `${target}%` }} transition={{ duration: run ? 3.1 + index * .13 : .5, ease: 'easeInOut' }} style={{ top: `${46 + index * 48}px`, color: branch.colour, '--trail': branch.colour } as React.CSSProperties}><CarFront size={33}/><span>{branch.code}</span></motion.div>; })}<div className="grand-finish"><Flag size={25}/><b>FINISH</b></div></div></div>{run > 0 && <><motion.div className="grand-result" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}><Zap size={16}/> DEMO RESULT: {ordered[0]?.name} holds P1 while every branch advances through the same verified-action race.</motion.div><RaceExplanation branches={ordered} mode="season"/></>}</section>;
}

function RivalryGrid({ branches }: { branches: Branch[] }) {
  const [swing, setSwing] = useState(0); const [running, setRunning] = useState(false); const display = useMemo(() => [...branches].map((branch, index) => ({ ...branch, score: branch.score + (swing && index === 1 ? Math.max(28, branches[0].score - branch.score + 9) : swing && index === 2 ? 12 : 0) })).sort((a, b) => b.score - a.score), [branches, swing]); const max = Math.max(...display.map(branch => branch.score), 1);
  const simulate = () => { setRunning(true); setSwing(value => value ? 0 : 1); window.setTimeout(() => setRunning(false), 2600); };
  return <section className="race-module rivalry-module rivalry-module--grand"><div className="module-heading"><span><Map size={16}/> BRANCH RIVALRY HEATMAP</span><button className="button button--ghost" onClick={simulate} disabled={running}><Zap size={14}/>{running ? 'Momentum shifting...' : swing ? 'Reset race order' : 'Simulate momentum swing'}</button></div><p className="module-copy">A living performance grid using normalized branch pace. During simulation, every energy bar surges and falls before a challenger overtakes - without corrupting the real leaderboard.</p><div className={`rivalry-grid rivalry-grid--animated${running ? ' is-shifting' : ''}`}>{display.map((branch, index) => <motion.article layout key={branch.code} className={`rivalry-cell rivalry-cell--${index % 4}`} transition={{ type: 'spring', stiffness: 190, damping: 18 }}><span><i style={{ background: branch.colour }}/> P{index + 1} / {branch.code}</span><strong>{branch.name}</strong><div><motion.i style={{ background: `linear-gradient(90deg, ${branch.colour}, #e9fb6b)` }} animate={{ width: running ? ['28%', '93%', `${Math.min(100, branch.score / max * 100)}%`] : `${Math.min(100, branch.score / max * 100)}%` }} transition={{ duration: 2.2, times: [0, .52, 1] }}/></div><b>{format.format(branch.score)} <small>PACE</small></b>{swing && index === 0 && <em>LEADERBOARD SWING</em>}</motion.article>)}</div><div className="rivalry-callout"><Zap size={15}/><span>{swing ? `${display[0]?.name} has demonstrated an overtake. Read the explanation below to show the judge why the order changed.` : 'Run the simulation to show all branches fighting for position.'}</span></div>{swing > 0 && <RaceExplanation branches={display} mode="rivalry"/>}</section>;
}

export function RaceControlPage() {
  const { session } = useAuth(); const token = session!.accessToken; const [briefing, setBriefing] = useState(true);
  const profile = useQuery({ queryKey: ['profile'], queryFn: () => getProfile(token) }); const branches = usePresentationLeaderboard(token, session!.employeeId, session!.expiresAt, 'branch'); const bookings = useQuery({ queryKey: ['race-control', 'bookings'], queryFn: () => getActiveBookings(token, profile.data?.department ?? undefined), enabled: !!profile.data?.department }); const quests = useQuery({ queryKey: ['race-control', 'quests'], queryFn: () => getQuests(token) }); const bosses = useQuery({ queryKey: ['race-control', 'bosses'], queryFn: () => getBosses(token) });
  if (session?.role === 'ADMIN') return <Navigate to="/app/admin" replace/>;
  const branchCards = useMemo<Branch[]>(() => (branches.data?.entries.slice(0, 8).map((entry, index) => ({ name: boardName(entry), score: boardScore(entry), code: String(entry.location_code ?? `BR${index + 1}`), colour: colours[index % colours.length] })) ?? fallbackBranches.map((branch, index) => ({ ...branch, colour: colours[index] }))), [branches.data]);
  const booking = bookings.data?.entries[0]; const mission = quests.data?.quests.find(item => !item.claimed); const boss = bosses.data?.battles.find(item => item.department === profile.data?.department) ?? bosses.data?.battles[0];
  return <PageMotion><main className="app-page race-control-page"><header className="race-control-header"><div><p className="eyebrow">RACE CONTROL / MULTI-BRANCH COMPETITION</p><h1>Watch the grid<br/><em>come alive.</em></h1><p>Live branch pace becomes a grand racing story. Every motion demo is safe, repeatable, and visibly separate from the verified leaderboard.</p></div><button className="race-brief-button" onClick={() => setBriefing(true)}><Gauge size={21}/><span>RACE ENGINEER</span><strong>Open briefing</strong></button></header><SeasonCircuit branches={branchCards}/><RivalryGrid branches={branchCards}/></main><Briefing open={briefing} close={() => setBriefing(false)} rank={profile.data?.all_time_rank} next={booking ? `${booking.enquiry_no} / ${booking.current_stage.replace(/_/g, ' ')}` : 'Check your Pit Wall'} mission={mission?.title ?? 'Choose a focus mission'} boss={boss?.title ?? 'Department rally'} department={profile.data?.department ?? 'dealership'}/></PageMotion>;
}
