import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Target, Trophy } from 'lucide-react';
import { useState } from 'react';
import { useAuth } from '../auth/AuthContext';
import { PageMotion } from '../../shared/PageMotion';
import { AchievementCinematic } from '../enhancements/GameEnhancements';
import { claimBoss, claimQuest, getBosses, getQuests } from '../dashboard/dashboardApi';
import type { Quest } from '../../types/api';

export function QuestsPage() {
  const token = useAuth().session!.accessToken; const client=useQueryClient(); const [open,setOpen]=useState<Quest|null>(null); const [reward,setReward]=useState('');
  const quests=useQuery({queryKey:['quests'],queryFn:()=>getQuests(token)});
  const claim=useMutation({mutationFn:(code:string)=>claimQuest(token,code),onSuccess:r=>{setReward(`Mission reward: +${r.reward_xp} XP`);setOpen(null);void client.invalidateQueries()}});
  return <PageMotion><header className="page-title"><p className="eyebrow">WEEKLY MISSION BOARD</p><h1>Make the next<br/><em>move count.</em></h1><p>Open a mission to see its exact verified action and reward. Selecting a mission awards nothing; claiming it only works after the real action arrives.</p></header><section className="quest-grid">{quests.data?.quests.map(q=><article className={`quest-card-full ${q.claimed?'claimed':''}`} key={q.code}><Target size={20}/><p className="eyebrow">{q.canonical_event.replace(/_/g,' ')}</p><h2>{q.title}</h2><p>{q.description}</p><div className="progress-track"><span style={{width:`${Math.min(100,q.progress/Math.max(1,q.target_count)*100)}%`}}/></div><div className="progress-caption"><span>{q.progress}/{q.target_count} verified</span><strong>+{q.reward_xp} XP</strong></div><button className="button button--ghost" onClick={()=>setOpen(q)}>Open mission</button>{q.claimed?<span className="claim-state"><Check size={15}/> Claimed</span>:<button className="button button--primary" disabled={!q.completed||claim.isPending} onClick={()=>claim.mutate(q.code)}>{q.completed?'Claim reward':'Complete verified action first'}</button>}</article>)}</section>{open&&<section className="achievement-overlay"><article className="achievement-card"><button onClick={()=>setOpen(null)}>×</button><Target size={50}/><p className="eyebrow">MISSION BRIEFING</p><h2>{open.title}</h2><p>{open.description}</p><p>Required: {open.target_count} × {open.canonical_event.replace(/_/g,' ')}. Reward: +{open.reward_xp} XP.</p></article></section>}<AchievementCinematic title={reward} open={!!reward} onClose={()=>setReward('')}/></PageMotion>;
}

export function BossBattlesPage() {
  const token=useAuth().session!.accessToken; const client=useQueryClient(); const [reward,setReward]=useState(''); const bosses=useQuery({queryKey:['bosses'],queryFn:()=>getBosses(token)}); const claim=useMutation({mutationFn:(id:string)=>claimBoss(token,id),onSuccess:r=>{setReward(`Boss reward claimed: +${r.points} XP · ${r.title}`);void client.invalidateQueries()},onError:()=>void client.invalidateQueries()});
  return <PageMotion><header className="page-title"><p className="eyebrow">DEPARTMENT BOSS BATTLES</p><h1>Win it <em>together.</em></h1><p>Contribute a verified department action, complete the team target, then claim your own share of the reward.</p></header><section className="boss-grid">{bosses.data?.battles.map(b=><article className="boss-card-full" key={b.id}><div className="boss-icon"><Trophy size={26}/></div><p className="eyebrow">{b.department} / {b.canonical_event.replace(/_/g,' ')}</p><h2>{b.title}</h2><p>{b.description}</p><div className="boss-bar"><span style={{width:`${Math.min(100,b.progress/Math.max(1,b.target_count)*100)}%`}}/></div><div className="progress-caption"><span>{b.progress}/{b.target_count} progress</span><strong>{b.remaining} remaining</strong></div><footer><span>{b.contributors} contributors</span><b>{b.reward_pool_xp} team XP</b></footer>{b.claimed?<span className="claim-state"><Check size={15}/> Reward claimed</span>:<button className="button button--primary" disabled={!b.eligible_to_claim||claim.isPending} onClick={()=>claim.mutate(b.id)}>{b.eligible_to_claim?'Claim boss reward':'Contribute to unlock claim'}</button>}{claim.error&&<small className="form-error">{claim.error.message}</small>}</article>)}</section><AchievementCinematic title={reward} artifact="Champion trophy" open={!!reward} onClose={()=>setReward('')}/></PageMotion>;
}
